name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "14.11.0"

      - name: Install Dependencies
        run: npm install

      - name: Run build
        run: npm build

      - name: Run test
        run: npm test
